Auth task
wolox-training/cy-rails pull request #5
Opened 2018-10-10 16:46 UTC by yanzacd

## Summary

Se adiciona la gema devise auth para la autenticacion de los usuarios

## Trello Card

https://trello.com/c/dVWvDezV/24-implementar-autenticación

2018-10-12 15:35 UTC, mtejedorwolox requested changes
you can't delete migrations once they have run. The correct way to do it is to create a new migration (without deleting the previous ones) and make there the changes you need for it to work properly.

2018-10-12 15:35 UTC, mtejedorwolox commented on config/routes.rb
> +  namespace :api do
use versionist `api_version`

2018-10-12 15:35 UTC, mtejedorwolox commented on Gemfile
> +gem 'omniauth', '~> 1.8', '>= 1.8.1'
why?

2018-10-12 15:36 UTC, mtejedorwolox requested changes

2018-10-12 15:36 UTC, mtejedorwolox commented on app/models/user.rb
> +          :trackable, :validatable, :confirmable, :omniauthable
remove confirmable and omniauthable

2018-10-12 16:36 UTC, yanzacd commented on config/routes.rb
> +  namespace :api do
Para usar el api_version seria de esta manera: (No estoy seguro)

namespace :api do
   mount_devise_token_auth_for 'User', at: 'auth'
      api_version(
        header: {
          name: 'Accept',
          value: 'application/vnd.versionist_api.v1+json'
        },
        module: 'V1',
        default: true,
        defaults: { format: :json }
      ) do
        resources :books, only: [:index, :show]
      end
    end
end

2018-10-12 16:39 UTC, yanzacd commented on Gemfile
> +gem 'omniauth', '~> 1.8', '>= 1.8.1'
Solo quito la gema de omniauth? o también la de devise_toke_auth ?

2018-10-16 18:41 UTC, mtejedorwolox approved these changes

2018-10-16 18:48 UTC, merged