Creacion modelo book
wolox-training/cy-rails pull request #6
Opened 2018-10-11 12:58 UTC by yanzacd

## Summary

Se genera el modelo Book y se realiza una inserción en la base de datos para la comprobación de la correcta creación del modelo.

## Trello Card

[https://trello.com/c/6p46QjGK/19-crear-modelo-de-book

2018-10-16 19:17 UTC, yanzacd commented
Ya paso el travis  quedo en la espera de la aprobación para hacer el merge PR

2018-10-17 17:08 UTC, mtejedorwolox requested changes

2018-10-17 17:08 UTC, mtejedorwolox commented on db/migrate/20181011124125_create_books.rb
> +      t.string :genero, null: false
genre, author, image, title, publisher, year

2018-10-17 17:08 UTC, mtejedorwolox commented on db/schema.rb
> +    t.integer "sign_in_count", default: 0, null: false
this changes doesn't belong to the migration

2018-10-17 17:08 UTC, mtejedorwolox commented on db/migrate/20181011124125_create_books.rb
> +      t.string :genero, null: false
and description

2018-10-17 17:08 UTC, mtejedorwolox commented on app/models/book.rb
> +class Book < ApplicationRecord
validate presence of genre, author, title, publisher, year

2018-10-17 18:22 UTC, mtejedorwolox submitted a review, later dismissed

2018-10-17 18:22 UTC, mtejedorwolox commented on app/models/book.rb
> +  validates :genre, :author, :image, :title, :publisher, :year, presence: true
remove validation of image

2018-10-17 18:22 UTC, mtejedorwolox commented on db/migrate/20181011124125_create_books.rb
> +      t.string :image, null: false
remove null: false

2018-10-17 18:28 UTC, mtejedorwolox approved these changes

2018-10-17 18:30 UTC, merged